services:
  - type: web
    name: imoradar
    runtime: node
    buildCommand: npm install && npx prisma generate && rm -rf .next && IMORADAR_BUILD=1 npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: GOBII_API_KEY
        sync: false
